base:
  mass: 0.8               # Base mass in Kg
  radius: 0.095           # Base radius in m (slightly smaller top layer)
  x_size: 0.19            # = 2*radius, used for wheel positioning
  y_size: 0.19            # = 2*radius, used for wheel positioning
  z_size: 0.02            # Top layer height in m
  mesh: ''                # Leave empty to use cylinder primitive
